### ISSUE TITLE
[Feature Request] Data Insertion Speed

### ISSUE THREAD

**Issue by jsmorganpm** [Geotab/mygeotab-api-adapter#1]
Given the large amount of data to be processed for some Geotab customers, it might be worth the time to look at bulk insertion solutions for inserting large amounts of data into the various databases.

**Comment by sdietz888** [comment]
Given that this solution is designed to support multiple databases with a single code base, it is not suited to bulk insertion solutions that are specific to individual database providers. However, since the solution is open source, someone could clone the repository and then modify it as required to add bulk insertion capabilities for their database of choice.
